### ISSUE TITLE
reverse sync (backup)

### ISSUE THREAD

**Issue by abdurrm** [v0tti/netbox-powerdns-sync#3]
can I sync the record FROM pdns to netbox-dns?
I have 3000 record  in our pdns, i need to back it up to our Netbox 
maybe i can use netbox DNS as SoT, so i dont have directly access to PDNS API

**Comment by v0tti** [comment]
At the moment only sync from NetBox is supported.
It would not be hard to do the reverse but I do not intend to implement it in this repository.
